### ISSUE TITLE
Consolidate information and communication

### ISSUE THREAD

**Issue by xanathon** [bussardrobbie/DDL-KB-Kanban#26] opened 2021-04-14 07:32 UTC
There is no recognizable communication and information strategy by DDL. Information - as documentation - is highly fragmented over half of the internet, but there is no central place to get news and information. A blog with rss feed was abandoned days after it's invention. The mailinglist sends senseless advertisement mails instead of informations that users would interest (I never got info about european distribution of Vector 2.0 despite having clearly critisized shipment only from USA, that was the information I would have expected via such an email). The Facebook group probably has more blocked users than users still in it. There are posts fragmented over Reddit and Discord. The old Anki forums. Kickstarter emails. Kickstarter comments. Most informations are only available on some of the platforms. This does not only look highly disorganized, it is highly disorganized and the fragmentation is not user-friendly at all.

Solution: A central information and communication hub, e.g. a blog that is categorized in a smart and organized way. On that blog all relevant infos and news are posted, users can subscribe to the news via an RSS feed or just visit the site regularily. From there news are posted to all the other media, that can be automated in many cases. Having this central information hub would take workload and pressure from the people at DDL as they would have to post informations just once instead of multiple places qand the infos are more or less automatically migrated to the other platforms. I did something like that for multiple of my customers.

This central information and communication hub needs to be on an openly accessible website instead of a walled garden like Facebook or Kickstarter comments. 

If this is implemented you would be able in the future for many user questions to just link to an already existing article.

**Comment by bussardrobbie** [comment] 2021-04-14 16:32
I am working to consolidate information into the Knowledge Base, hence the creation of this repository. I am seeking specific examples of ongoing user experience impacting items that may not already be documented, or that are scattered and not cohesively placed in the Knowledge Base.

Some fragmentation is expected through corporate transitions and this fragmentation will decrease over time; we are putting new policies and practices into place to streamline communications. I am also examining options for documentation that can be community-contributed. This is the first step into that evolution, where I consolidate information and get it all into one place before I consider additional options for documentation platforms and begin a full restructuring of that documentation for cohesion.

Your other feedback regarding emails or other practices is noted; however this repository is not the place for general feedback on practices unrelated to, specifically, knowledge base documentation. Reference the existing issues that I have placed in this repository for examples on how to submit specific issues.

**Comment by bussardrobbie** [comment] 2021-04-14 18:16
Closing issue as, effectively, a duplicate of #25

**Closed as completed by bussardrobbie** 2021-04-14 18:16 UTC

**Comment by xanathon** [comment] 2021-04-14 18:59
The existing knowledge base is not an acceptable solution due to the deficiencies in UI and UX missing treelike subnavigation and general user friendlyness.

And there is a distinct difference between (communication and information) and documentation, so I cannot understand how you can possibly think this is a duplicate. But maybe the inability to see the difference is part of the problem.

Just closing suggestions without really adressing them is the behaviour I expected here, to be honest.

Not a duplicate at all.

**Comment by xanathon** [comment] 2021-04-14 19:10
On another note: You told me on Discord to take my remarks and suggestions for multiple problems here. And if I do so you close them because they "do not fit here" and without giving an option where to report them so they fit better. Seriously? There is no better way to demonstrate that you are actually not interested in opinions.

**Comment by bussardrobbie** [comment] 2021-04-14 19:56
My prior comment states the following: "This is the first step into that evolution, where I consolidate information and get it all into one place before I consider additional options for documentation platforms and begin a full restructuring of that documentation for cohesion."

My wording on Discord was the following: "Open an issue with this repo with specific requests if you want to see or recommend changes in the documentation..."

Again, the other feedback is noted but is not applicable to this repository. Our conversations combined with the examples in this repository clearly outline the parameters of the feedback I am looking for at the current moment so that I can form a plan for the longer term. Hence the documentation solution we have (the Knowledge Base at support.digitaldreamlabs.com) is the one we are working on in this repository- if I need to spell that out more clearly in the README, I am glad to do so.
